Repository FRCDiscord/Dozer, pull requests merged in 2020-12, with the labels that each got.

#241 Removed last evidence of travis(ci)
  README.md
Labels: enhancement

#242 Fix race condition of two reactions in quick succession for starboard
  dozer/cogs/starboard.py
Labels: bug

#238 Removed invite command, added option to disable automatic team number nicknames
  dozer/cogs/general.py
  dozer/cogs/teams.py
Labels: bug, enhancement

#240 Added reaction based deletes for the giveme command
  dozer/cogs/roles.py
Labels: enhancement

#245 Reaction roles patch 1
  dozer/cogs/general.py
  dozer/cogs/roles.py
Labels: bug

#246 Removed cache from reaction roles
  dozer/cogs/roles.py
Labels: bug

#236 Added raw event handler to hof
  dozer/cogs/starboard.py
Labels: enhancement

#244 News error handling
  dozer/cogs/news.py
Labels: bug, enhancement

#249 Fixed mutes not including duration in the modlog
  dozer/cogs/moderation.py
Labels: bug

#247 New Member Purges
  dozer/cogs/moderation.py
Labels: enhancement

#248 Levels feature 3
  dozer/cogs/levels.py
Labels: enhancement

#252 Fixed issue where Hof wouldn't see custom reacts
  dozer/cogs/starboard.py
Labels: bug

#255 Fixed bug with autoteam
  dozer/cogs/teams.py
Labels: bug

#256 Fixed small bug with filter command
  dozer/cogs/filter.py
Labels: bug

#259 Info upgrades
  dozer/cogs/general.py
  dozer/cogs/info.py
  dozer/cogs/levels.py
  dozer/cogs/moderation.py
Labels: enhancement

#260 Bulk delete logs
  dozer/cogs/moderation.py
  pylintrc
Labels: enhancement

#265 Levels Features 3
  dozer/cogs/levels.py
  dozer/cogs/starboard.py
Labels: enhancement

#266 Levels patch 4
  dozer/cogs/levels.py
Labels: bug, enhancement

#262 Moderation refractro
  dozer/cogs/actionlogs.py
  dozer/cogs/moderation.py
  dozer/cogs/roles.py
Labels: enhancement
