Repository FRCDiscord/Dozer, pull requests merged in 2021-02, with the labels that each got.

#279 Newsfeed spam de-spammer
  dozer/cogs/news.py
Labels: bug, enhancement

#288 Added more to the regex, and changed the wording of the mod logs
  dozer/cogs/moderation.py
Labels: enhancement

#281 Music
  docker-compose.yml
  dozer/__main__.py
  dozer/cogs/actionlogs.py
  dozer/cogs/music.py
  pylintrc
  requirements.txt
Labels: enhancement

#290 Added channel id to the edit log footer
  dozer/cogs/actionlogs.py
Labels: enhancement

#284 Added message ID to cahced message delete embed
  dozer/cogs/actionlogs.py
Labels: enhancement

#285 Reduce selfdeafen spam
  dozer/bot.py
  dozer/cogs/moderation.py
Labels: enhancement

#287 Levels feature update 5
  dozer/cogs/levels.py
Labels: enhancement

#289 Added purge filter, and fixed bug in message logging
  dozer/cogs/actionlogs.py
  dozer/cogs/moderation.py
Labels: bug, enhancement

#292 Added removefromqueue command
  dozer/cogs/music.py
Labels: enhancement

#295 Moved nm_kick to the end of on_ready because it's stuck
  dozer/cogs/moderation.py
Labels: bug

#294 Fix issue with log, and formatting
  dozer/cogs/actionlogs.py
Labels: bug, enhancement

#297 Implement slash commands
  dozer/__main__.py
  dozer/bot.py
  dozer/cogs/_utils.py
  dozer/cogs/info.py
  dozer/cogs/levels.py
  requirements.txt
Labels: enhancement
