Repository FRCDiscord/Dozer, pull requests merged in 2021-04, with the labels that each got.

#314 changed readme and gitignore a bit
  .gitignore
  README.md
  static/createbot.png
  static/createbot1.png
  static/createbot2.png
  static/intents.png
  static/invite1_scopes.png
  static/invite2_permissions.png
  static/invite3_oauthurl.png
  static/newapp.png
  static/tokens.png
Labels: enhancement

#312 Update weather
  docs/Actionlog.rst
  docs/Filter.rst
  docs/Fun.rst
  docs/Levels.rst
  docs/Music.rst
  docs/NameGame.rst
  docs/News.rst
  docs/Roles.rst
  docs/Starboard.rst
  docs/TBA.rst
  docs/_build/doctrees/Actionlog.doctree
  docs/_build/doctrees/Filter.doctree
  docs/_build/doctrees/Fun.doctree
  docs/_build/doctrees/Levels.doctree
  docs/_build/doctrees/Music.doctree
  docs/_build/doctrees/NameGame.doctree
  docs/_build/doctrees/News.doctree
  docs/_build/doctrees/Roles.doctree
  docs/_build/doctrees/Starboard.doctree
  docs/_build/doctrees/TBA.doctree
  docs/_build/doctrees/environment.pickle
  docs/_build/html/Actionlog.html
  docs/_build/html/Development.html
  docs/_build/html/Filter.html
  docs/_build/html/Fun.html
  docs/_build/html/General.html
  docs/_build/html/Info.html
  docs/_build/html/Levels.html
  docs/_build/html/Maintenance.html
  docs/_build/html/Moderation.html
  docs/_build/html/Music.html
  docs/_build/html/NameGame.html
  docs/_build/html/News.html
  docs/_build/html/Roles.html
  docs/_build/html/Starboard.html
  docs/_build/html/TBA.html
  docs/_build/html/TOA.html
  docs/_build/html/Teams.html
  docs/_build/html/Voice.html
  docs/_build/html/_sources/Actionlog.rst.txt
  docs/_build/html/_sources/Filter.rst.txt
  docs/_build/html/_sources/Fun.rst.txt
  docs/_build/html/_sources/Levels.rst.txt
  docs/_build/html/_sources/Music.rst.txt
  docs/_build/html/_sources/NameGame.rst.txt
  docs/_build/html/_sources/News.rst.txt
  docs/_build/html/_sources/Roles.rst.txt
  docs/_build/html/_sources/Starboard.rst.txt
  docs/_build/html/_sources/TBA.rst.txt
  docs/_build/html/genindex.html
  docs/_build/html/index.html
  docs/_build/html/search.html
  docs/_build/html/searchindex.js
  dozer/cogs/moderation.py
  dozer/cogs/tba.py
Labels: bug, enhancement

#313 Punishment list
  dozer/cogs/moderation.py
Labels: enhancement

#315 Cross bans
  dozer/cogs/moderation.py
  dozer/db.py
Labels: enhancement

#317 Allow for disabling cogs in the configuration
  dozer/__main__.py
Labels: enhancement

#316 Formatting go brrrrrr
  README.md
Labels: bug

#319 Fixed perm override permissions check
  dozer/cogs/moderation.py
Labels: bug

#320 Ok if you can't fix the error, just ignore it
  dozer/cogs/moderation.py
Labels: bug

#321 Removed futures bundling in overwrite updates
  dozer/cogs/moderation.py
Labels: Urgent, bug

#322 Role slash commands
  dozer/cogs/roles.py
Labels: enhancement

#323 Nickname filter and nickname lock
  dozer/cogs/actionlogs.py
  dozer/cogs/filter.py
  dozer/cogs/moderation.py
Labels: enhancement

#324 I may be a fool
  dozer/cogs/actionlogs.py
Labels: bug
