Repository FRCDiscord/Dozer, pull requests merged in 2022-07, with the labels that each got.

#357 Type checking
  .gitignore
  dozer/__main__.py
  dozer/bot.py
  dozer/cogs/_utils.py
  dozer/cogs/actionlogs.py
  dozer/cogs/development.py
  dozer/cogs/filter.py
  dozer/cogs/fun.py
  dozer/cogs/general.py
  dozer/cogs/info.py
  dozer/cogs/levels.py
  dozer/cogs/maintenance.py
  dozer/cogs/management.py
  dozer/cogs/moderation.py
  dozer/cogs/music.py
  dozer/cogs/namegame.py
  dozer/cogs/news.py
  dozer/cogs/roles.py
  dozer/cogs/starboard.py
  dozer/cogs/tba.py
  dozer/cogs/teams.py
  dozer/cogs/toa.py
  dozer/cogs/voice.py
  dozer/context.py
  dozer/db.py
  dozer/sources/AbstractSources.py
  dozer/sources/RSSSources.py
  dozer/sources/RedditSource.py
  dozer/sources/TwitchSource.py
  dozer/sources/__init__.py
  requirements.txt
Labels: enhancement

#380 Fix lint and autoreveiw
  .github/workflows/main.yml
Labels: bug

#379 Fix double sending member join logs
  dozer/Components/CustomJoinLeaveMessages.py
  dozer/cogs/actionlogs.py
  dozer/cogs/moderation.py
  requirements.txt
Labels: bug

#367 Sanitation fix
  dozer/cogs/actionlogs.py
  dozer/cogs/fun.py
  dozer/cogs/general.py
  dozer/cogs/info.py
  dozer/cogs/levels.py
  dozer/cogs/management.py
  dozer/cogs/moderation.py
  dozer/cogs/namegame.py
  dozer/cogs/roles.py
  dozer/cogs/starboard.py
  dozer/cogs/tba.py
  dozer/cogs/teams.py
  dozer/cogs/toa.py
  dozer/cogs/voice.py
Labels: bug, enhancement
